### ISSUE TITLE
What is intended by  "tsʔ" ?

### ISSUE THREAD

**Issue by XachaB** [lexibank/joophonosemantic#10]
For the sound correspondence study, I get a lot of occurences of "tsʔ" from this dataset, but it is not a valid BIPA symbol. Is it possible to remap it to something valid ? 

EDIT: I just saw that the script remaps 'tʃʔ' to 'tʃˀ' (not sure why it is not directly in the orthography profile), maybe the same exact thing is needed here ?

**Comment by LinguList** [comment]
I think the best is to make an orthography profile. You could just use all symbols you find there, and then refine them. You would just resolve the `.` as being converted to NONE, and that would do the trick.

**Comment by XachaB** [comment]
Ah, I had not realized that there is not an orthography profile yet. I can take care of it if that's ok with everyone involved, and only do what is currently done in the script + tsʔ to tʃˀ.

The TRANSCRIPTION file finds a few other problems, but I am not an expert at all, so I can't guess what should be done:


Segment | Occurrence | BIPA | CLTS SoundClass
-- | -- | -- | --
ǀn | 4 | ? | ?
aʰ | 3 | ? | ?
g\| | 3 | ? | ?
g‖ | 3 | ? | ?
n\| | 3 | ? | ?
tlʼ | 3 | ? | ?
uʰ | 3 | ? | ?
ǂn | 3 | ? | ?
ɡ | 3 | ? | ?
iʰ | 2 | ? | ?
n‖ | 2 | ? | ?
n | 2 | ? | ?
pr | 2 | ? | ?
tsʔ | 2 | ? | ?
ɡʰ | 2 | ? | ?
‖ | 2 | ? | ?
!n | 1 | ? | ?
Q | 1 | ? | ?
eʰ | 1 | ? | ?
n!ʰ | 1 | ? | ?
rĩ | 1 | ? | ?
tl | 1 | ? | ?
tʃxˀ | 1 | ? | ?
uʔ | 1 | ? | ?
\| | 1 | ? | ?
\|ʔʰ | 1 | ? | ?
ǁn | 1 | ? | ?
ɡ‖xˀ | 1 | ? | ?
ʔl | 1 | ? | ?
ʔn | 1 | ? | ?
̃ĩ | 1 | ? | ?
‖x | 1 | ? | ?
‖xˀ | 1 | ? | ?
‖ʔ | 1 | ? | ?
‖ʔʰ | 1 | ? | ?
‖ʰ | 1 | ? | ?
ʔʰ | 1 | ? | ?


@ianjoo, could you review these and suggest transcriptions ?

**Comment by LinguList** [comment]
@tresoldi, you also looked at those click languages in phoible etc., can you help here?

**Comment by tresoldi** [comment]
Most are cases of Unicode homoglyphs, like U+2016 instead of U+01C1 for lateral click.

Should I make a PR and have @ianjoo review it?

**Comment by tresoldi** [comment]
Oh, I missed that there is no profile; maybe we should just build a list of lexemes? Or even fix the raw data directly?

**Comment by XachaB** [comment]
Can't all of this be solved by creating a profile ? If so, I would think that's the cleanest way.

**Comment by LinguList** [comment]
Didn't I say exactly this? You make a profile, using all segments, and
declare `.` as being replaced by `NONE`.

**Comment by tresoldi** [comment]
I will do it

**Comment by XachaB** [comment]
This is solved by the profile, thanks !
