### ISSUE TITLE
bookkeeping language:  Chuanqiandian Cluster Miao chua1256

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/joophonosemantic#3]
Can we identify this better?

**Comment by LinguList** [comment]
* https://glottolog.org/resource/languoid/id/chua1248

This is my suggestion.

**Comment by LinguList** [comment]
@ianjoo, do you remember from the source if it allows for a closer classification in terms of glottolog?

**Comment by ianjoo** [comment]
The standard dialect of Chuanqiandian Cluster Miao is the variety spoken in Dananshan (Bijie, Guizhou)and all the Chinese sources I have consulted made reference to this variety. Glottolog does not seem to have a particular page for Dananshan Miao.

**Comment by LinguList** [comment]
Okay, so there are two things we can do here now:

1. what is the next higher glottocode (in the new version)?
2. you could file an issue, providing your source (in bibtex) along with a proposed name plus a geographic location to Harald on glottolog (https://github.com/glottolog/glottolog/issues), and they can add this to glottolog for the next version

Once 2. is done, you can get back to us and tell us the new glottocode, but for the time being, we would use the next larger node in the glottolog tree (as we also do with other dialects).

**Comment by CMUgarte** [comment]
I followed this workflow and propose: [First Vernacular Hmong](https://glottolog.org/resource/languoid/id/firs1234) as the next higher glottocode for the Dananshan Miao language in this dataset. I also opened an issue on Glottolog regarding this. So I'm closing the issue.
