### ISSUE TITLE
modify title and correct citation

### ISSUE THREAD

**Issue by LinguList** [lexibank/joophonosemantic#5]
```
@Article{Joo2019,
  title   = {Phonosemantic biases found in Leipzig-Jakarta lists of 66 languages},
  doi     = {10.1515/lingty-2019-0030},
  number  = {0},
  pages   = {1-12},
  volume  = {0},
  journal = {Linguistic Typology},
  year    = {2019},
}
```

@chrzyki, if you add the sources anyway, could you take over? You could just assign yourself as patron here.

**Comment by LinguList** [comment]
Note that this is still ahead of print. Once it is published, the year will change to 2020.

**Comment by chrzyki** [comment]
Yes, will take over and assign myself as patron.
