### ISSUE TITLE
fly

### ISSUE THREAD

**Issue by ianjoo** [lexibank/joophonosemantic#6]
The concept “fly” refers to the insect, not the verb to fly.

**Comment by LinguList** [comment]
Ah, you see how important it is to be explicit and linking the data to concepticon. [fly](https://concepticon.clld.org/values/Tadmor-2009-100-20) in leipzig-jakarta **is** the verb.

This needs to be handled on concpeticon then, could you add an issue to [concepticon-data/](https://github.com/concepticon/concepticon-data/issues)?

**Comment by ianjoo** [comment]
I’m pretty sure it’s the insect in LJ. It’s “fly”, not “**to** fly”, and it’s mentioned as the insect in Tadmor 2009.

**Comment by ianjoo** [comment]
![96B89658-81AC-441D-9F7F-89F694170906](https://user-images.githubusercontent.com/32216912/80229327-3a01e400-868b-11ea-85f8-a35041678897.jpeg)

**Comment by LinguList** [comment]
then we need to modify this in concepticon, thanks for spotting it.

**Comment by chrzyki** [comment]
Done.
